### ISSUE TITLE
[Bug]: PCF Builder does not start

### ISSUE THREAD

**Issue by ShazzyImperium** [Power-Maverick/PCF-CustomControlBuilder#66]
### Contact Details

shahzar.khalid@imperiumdynamics.com

### What happened?

On opening it gives the following error:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Maverick.PCF.Builder.PCFBuilder.PopulateControlDetails()
   at Maverick.PCF.Builder.PCFBuilder.tsbEditControl_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### What version of the tool are you using?

2.2023.3.201

### What version of XrmToolBox are you running?

1.2023.2.64

### Relevant log output

```shell
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Maverick.PCF.Builder.PCFBuilder.PopulateControlDetails()
   at Maverick.PCF.Builder.PCFBuilder.tsbEditControl_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Power-Maverick** [comment]
Unable to recreate the issue. Need more details.

**Comment by MatthewTheRaven** [comment]
An easy way to reproduce this is just to choose a control with a valid directory, then close the tool. Edit the Maverick.PCF.Builder.xml settings and modify the WorkingDirectoryLocation entry to a non-valid location. Then launch the tool and it will show a null reference error and crash XRMToolbox.
